# coding: utf-8

"""
    Billingo API v3

    This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.

    The version of the OpenAPI document: 3.0.14
    Contact: hello@billingo.hu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_billingo.api.spending_api import SpendingApi  # noqa: E501


class TestSpendingApi(unittest.TestCase):
    """SpendingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SpendingApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_spending_delete(self) -> None:
        """Test case for spending_delete

        Deletes a spending.  # noqa: E501
        """
        pass

    def test_spending_list(self) -> None:
        """Test case for spending_list

        Lists all spending  # noqa: E501
        """
        pass

    def test_spending_save(self) -> None:
        """Test case for spending_save

        Creates a new spending.  # noqa: E501
        """
        pass

    def test_spending_show(self) -> None:
        """Test case for spending_show

        Retrieves one specific spending.  # noqa: E501
        """
        pass

    def test_spending_update(self) -> None:
        """Test case for spending_update

        Updates a spending item.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
