# coding: utf-8

"""
    Billingo API v3

    This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.

    The version of the OpenAPI document: 3.0.14
    Contact: hello@billingo.hu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class CheckTaxNumberMessage(str, Enum):
    """
    CheckTaxNumberMessage
    """

    """
    allowed enum values
    """
    EXTERNAL_NAV_SERVICE_UNREACHABLE = 'external_nav_service_unreachable'
    INVALID_TAX_NUMBER = 'invalid_tax_number'
    NO_ONLINE_SZAMLA_SETTINGS = 'no_online_szamla_settings'
    NON_EXIST_TAX_NUMBER = 'non_exist_tax_number'
    VALIDATION_OK = 'validation_ok'

    @classmethod
    def from_json(cls, json_str: str) -> CheckTaxNumberMessage:
        """Create an instance of CheckTaxNumberMessage from a JSON string"""
        return CheckTaxNumberMessage(json.loads(json_str))


