# coding: utf-8

"""
    Billingo API v3

    This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.

    The version of the OpenAPI document: 3.0.14
    Contact: hello@billingo.hu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class DocumentNotificationStatus(str, Enum):
    """
    DocumentNotificationStatus
    """

    """
    allowed enum values
    """
    CLOSED = 'closed'
    DOWNLOADED = 'downloaded'
    FAILED = 'failed'
    NONE = 'none'
    OPENED = 'opened'
    READED = 'readed'

    @classmethod
    def from_json(cls, json_str: str) -> DocumentNotificationStatus:
        """Create an instance of DocumentNotificationStatus from a JSON string"""
        return DocumentNotificationStatus(json.loads(json_str))


