# coding: utf-8

"""
    Billingo API v3

    This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.

    The version of the OpenAPI document: 3.0.14
    Contact: hello@billingo.hu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, StrictInt, StrictStr, conlist
from clientapi_billingo.models.address import Address
from clientapi_billingo.models.partner_tax_type import PartnerTaxType

class DocumentPartner(BaseModel):
    """
    DocumentPartner
    """
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    address: Optional[Address] = None
    emails: Optional[conlist(StrictStr)] = None
    taxcode: Optional[StrictStr] = None
    iban: Optional[StrictStr] = None
    swift: Optional[StrictStr] = None
    account_number: Optional[StrictStr] = None
    phone: Optional[StrictStr] = None
    tax_type: Optional[PartnerTaxType] = None
    __properties = ["id", "name", "address", "emails", "taxcode", "iban", "swift", "account_number", "phone", "tax_type"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DocumentPartner:
        """Create an instance of DocumentPartner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DocumentPartner:
        """Create an instance of DocumentPartner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DocumentPartner.parse_obj(obj)

        _obj = DocumentPartner.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "address": Address.from_dict(obj.get("address")) if obj.get("address") is not None else None,
            "emails": obj.get("emails"),
            "taxcode": obj.get("taxcode"),
            "iban": obj.get("iban"),
            "swift": obj.get("swift"),
            "account_number": obj.get("account_number"),
            "phone": obj.get("phone"),
            "tax_type": obj.get("tax_type")
        })
        return _obj


