# coding: utf-8

"""
    Billingo API v3

    This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.

    The version of the OpenAPI document: 3.0.14
    Contact: hello@billingo.hu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from typing import List, Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr, conlist
from clientapi_billingo.models.currency import Currency
from clientapi_billingo.models.discount import Discount
from clientapi_billingo.models.document_insert_items_inner import DocumentInsertItemsInner
from clientapi_billingo.models.document_insert_type import DocumentInsertType
from clientapi_billingo.models.document_language import DocumentLanguage
from clientapi_billingo.models.document_settings import DocumentSettings
from clientapi_billingo.models.payment_method import PaymentMethod

class DocumentInsert(BaseModel):
    """
    DocumentInsert
    """
    vendor_id: Optional[StrictStr] = None
    partner_id: StrictInt = Field(...)
    block_id: StrictInt = Field(...)
    bank_account_id: Optional[StrictInt] = None
    type: DocumentInsertType = Field(...)
    fulfillment_date: date = Field(...)
    due_date: date = Field(...)
    payment_method: PaymentMethod = Field(...)
    language: DocumentLanguage = Field(...)
    currency: Currency = Field(...)
    conversion_rate: Optional[Union[StrictFloat, StrictInt]] = None
    electronic: Optional[StrictBool] = False
    paid: Optional[StrictBool] = False
    items: Optional[conlist(DocumentInsertItemsInner)] = None
    comment: Optional[StrictStr] = None
    settings: Optional[DocumentSettings] = None
    advance_invoice: Optional[conlist(StrictInt)] = None
    discount: Optional[Discount] = None
    instant_payment: Optional[StrictBool] = None
    __properties = ["vendor_id", "partner_id", "block_id", "bank_account_id", "type", "fulfillment_date", "due_date", "payment_method", "language", "currency", "conversion_rate", "electronic", "paid", "items", "comment", "settings", "advance_invoice", "discount", "instant_payment"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DocumentInsert:
        """Create an instance of DocumentInsert from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item in self.items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of discount
        if self.discount:
            _dict['discount'] = self.discount.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DocumentInsert:
        """Create an instance of DocumentInsert from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DocumentInsert.parse_obj(obj)

        _obj = DocumentInsert.parse_obj({
            "vendor_id": obj.get("vendor_id"),
            "partner_id": obj.get("partner_id"),
            "block_id": obj.get("block_id"),
            "bank_account_id": obj.get("bank_account_id"),
            "type": obj.get("type"),
            "fulfillment_date": obj.get("fulfillment_date"),
            "due_date": obj.get("due_date"),
            "payment_method": obj.get("payment_method"),
            "language": obj.get("language"),
            "currency": obj.get("currency"),
            "conversion_rate": obj.get("conversion_rate"),
            "electronic": obj.get("electronic") if obj.get("electronic") is not None else False,
            "paid": obj.get("paid") if obj.get("paid") is not None else False,
            "items": [DocumentInsertItemsInner.from_dict(_item) for _item in obj.get("items")] if obj.get("items") is not None else None,
            "comment": obj.get("comment"),
            "settings": DocumentSettings.from_dict(obj.get("settings")) if obj.get("settings") is not None else None,
            "advance_invoice": obj.get("advance_invoice"),
            "discount": Discount.from_dict(obj.get("discount")) if obj.get("discount") is not None else None,
            "instant_payment": obj.get("instant_payment")
        })
        return _obj


