# coding: utf-8

"""
    Billingo API v3

    This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.

    The version of the OpenAPI document: 3.0.14
    Contact: hello@billingo.hu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr
from clientapi_billingo.models.entitlement import Entitlement
from clientapi_billingo.models.vat import Vat

class DocumentItem(BaseModel):
    """
    DocumentItem
    """
    product_id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    net_unit_amount: Optional[Union[StrictFloat, StrictInt]] = None
    quantity: Optional[Union[StrictFloat, StrictInt]] = None
    unit: Optional[StrictStr] = None
    net_amount: Optional[Union[StrictFloat, StrictInt]] = None
    gross_amount: Optional[Union[StrictFloat, StrictInt]] = None
    vat: Optional[Vat] = None
    vat_amount: Optional[Union[StrictFloat, StrictInt]] = None
    entitlement: Optional[Entitlement] = None
    comment: Optional[StrictStr] = None
    __properties = ["product_id", "name", "net_unit_amount", "quantity", "unit", "net_amount", "gross_amount", "vat", "vat_amount", "entitlement", "comment"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DocumentItem:
        """Create an instance of DocumentItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if product_id (nullable) is None
        # and __fields_set__ contains the field
        if self.product_id is None and "product_id" in self.__fields_set__:
            _dict['product_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DocumentItem:
        """Create an instance of DocumentItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DocumentItem.parse_obj(obj)

        _obj = DocumentItem.parse_obj({
            "product_id": obj.get("product_id"),
            "name": obj.get("name"),
            "net_unit_amount": obj.get("net_unit_amount"),
            "quantity": obj.get("quantity"),
            "unit": obj.get("unit"),
            "net_amount": obj.get("net_amount"),
            "gross_amount": obj.get("gross_amount"),
            "vat": obj.get("vat"),
            "vat_amount": obj.get("vat_amount"),
            "entitlement": obj.get("entitlement"),
            "comment": obj.get("comment")
        })
        return _obj


