# coding: utf-8

"""
    Billingo API v3

    This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.

    The version of the OpenAPI document: 3.0.14
    Contact: hello@billingo.hu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr
from clientapi_billingo.models.entitlement import Entitlement
from clientapi_billingo.models.unit_price_type import UnitPriceType
from clientapi_billingo.models.vat import Vat

class DocumentProductData(BaseModel):
    """
    DocumentProductData
    """
    name: StrictStr = Field(...)
    unit_price: Union[StrictFloat, StrictInt] = Field(...)
    unit_price_type: UnitPriceType = Field(...)
    quantity: Union[StrictFloat, StrictInt] = Field(...)
    unit: StrictStr = Field(...)
    vat: Vat = Field(...)
    comment: Optional[StrictStr] = None
    entitlement: Optional[Entitlement] = None
    __properties = ["name", "unit_price", "unit_price_type", "quantity", "unit", "vat", "comment", "entitlement"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DocumentProductData:
        """Create an instance of DocumentProductData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DocumentProductData:
        """Create an instance of DocumentProductData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DocumentProductData.parse_obj(obj)

        _obj = DocumentProductData.parse_obj({
            "name": obj.get("name"),
            "unit_price": obj.get("unit_price"),
            "unit_price_type": obj.get("unit_price_type"),
            "quantity": obj.get("quantity"),
            "unit": obj.get("unit"),
            "vat": obj.get("vat"),
            "comment": obj.get("comment"),
            "entitlement": obj.get("entitlement")
        })
        return _obj


