# coding: utf-8

"""
    Billingo API v3

    This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.

    The version of the OpenAPI document: 3.0.14
    Contact: hello@billingo.hu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from typing import List, Optional
from pydantic import BaseModel, StrictBool, StrictStr, conlist
from clientapi_billingo.models.document_insert_items_inner import DocumentInsertItemsInner
from clientapi_billingo.models.payment_method import PaymentMethod

class ModificationDocumentInsert(BaseModel):
    """
    ModificationDocumentInsert
    """
    due_date: Optional[date] = None
    comment: Optional[StrictStr] = None
    payment_method: Optional[PaymentMethod] = None
    without_financial_fulfillment: Optional[StrictBool] = False
    items: Optional[conlist(DocumentInsertItemsInner)] = None
    __properties = ["due_date", "comment", "payment_method", "without_financial_fulfillment", "items"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ModificationDocumentInsert:
        """Create an instance of ModificationDocumentInsert from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item in self.items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ModificationDocumentInsert:
        """Create an instance of ModificationDocumentInsert from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ModificationDocumentInsert.parse_obj(obj)

        _obj = ModificationDocumentInsert.parse_obj({
            "due_date": obj.get("due_date"),
            "comment": obj.get("comment"),
            "payment_method": obj.get("payment_method"),
            "without_financial_fulfillment": obj.get("without_financial_fulfillment") if obj.get("without_financial_fulfillment") is not None else False,
            "items": [DocumentInsertItemsInner.from_dict(_item) for _item in obj.get("items")] if obj.get("items") is not None else None
        })
        return _obj


