# coding: utf-8

"""
    Billingo API v3

    This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.

    The version of the OpenAPI document: 3.0.14
    Contact: hello@billingo.hu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, StrictStr, conlist
from clientapi_billingo.models.online_szamla_status_message import OnlineSzamlaStatusMessage

class OnlineSzamlaStatus(BaseModel):
    """
    OnlineSzamlaStatus
    """
    transaction_id: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    messages: Optional[conlist(OnlineSzamlaStatusMessage)] = None
    __properties = ["transaction_id", "status", "messages"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OnlineSzamlaStatus:
        """Create an instance of OnlineSzamlaStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in messages (list)
        _items = []
        if self.messages:
            for _item in self.messages:
                if _item:
                    _items.append(_item.to_dict())
            _dict['messages'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OnlineSzamlaStatus:
        """Create an instance of OnlineSzamlaStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OnlineSzamlaStatus.parse_obj(obj)

        _obj = OnlineSzamlaStatus.parse_obj({
            "transaction_id": obj.get("transaction_id"),
            "status": obj.get("status"),
            "messages": [OnlineSzamlaStatusMessage.from_dict(_item) for _item in obj.get("messages")] if obj.get("messages") is not None else None
        })
        return _obj


